<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_TestSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fab26716-a2b0-4c4c-a6bb-333c6f523fef</testSuiteGuid>
   <testCaseLink>
      <guid>5c8b7454-13af-4bfd-872b-d4179817dabd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_006_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff16a970-887a-40fe-9b6f-f609fa0bb9c4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ff16a970-887a-40fe-9b6f-f609fa0bb9c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>f3a0614a-9763-4b75-97e4-5a4c7dd8a817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff16a970-887a-40fe-9b6f-f609fa0bb9c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>bb1cb5c6-3335-4c4a-9ae9-e646906eb29a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff16a970-887a-40fe-9b6f-f609fa0bb9c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ExpectedResult</value>
         <variableId>4b51b77a-fff2-4bf6-bad0-b3a480533534</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
